Created the Main Category Section.
sliitsesc/rheumaconnect-fe pull request #24
Opened 2024-12-24 05:23 UTC by IT22202468

Created 2 files named 'MainCatSection.jsx' and 'categoriesData.json'. 'MainCatSection.jsx' is the component and 'categoriesData.json' holds its data.

2024-12-24 05:25 UTC, pawan-live commented
@IT22202468 can you add screenshots (mobile/desktop)

2024-12-24 05:25 UTC, pawan-live commented
@Movin21 pls test the feature

2024-12-24 05:32 UTC, pawan-live requested changes
Looks good, I've left some comments pls address

2024-12-24 05:32 UTC, pawan-live commented on public/MainCatSection/mainCatImg_1.png
I thinnk the border radius should be applied from code, and use higher quality images on these if you have access to figma file, or get it via a designer 

@SandaliDisara FYI

2024-12-24 05:32 UTC, pawan-live commented on src/app/components/MainCatSection.jsx
> +    <Image src={src} alt={alt} width={274} height={103} />
Does this give responsive behavior for images? You may have to use tailwind classes here
And always have the object fit property to 'cover' in these scenarios

2024-12-24 05:32 UTC, pawan-live commented on src/app/components/MainCatSection.jsx
> +  <div className="p-8 cursor-pointer">
Why not use flexbox here? 👀

2024-12-24 05:32 UTC, pawan-live commented on src/app/components/MainCatSection.jsx
> +      {/* Categories Div */}
Actually we don't need these kind of comments 😄 but if it is a complex component it is the way to go

2024-12-24 05:32 UTC, pawan-live commented on src/app/components/MainCatSection.jsx
Shall we rename the file to MainCategorySection or something like that?

2024-12-24 09:47 UTC, Movin21 commented
> @Movin21 pls test the feature

I think the Highlight Behavior is missing for the category cards

Design File
![image](https://github.com/user-attachments/assets/7024518c-f487-42bb-b524-98473a23dce1)

2024-12-24 14:14 UTC, IT22202468 commented
Made changes as requested. Still images are low quality once. I asked from @SandaliDisara . After she sent the images I will replace the images. 

Web
![image](https://github.com/user-attachments/assets/4d5b997d-ad75-4261-ae62-3305a254858c)

Mobile
![image](https://github.com/user-attachments/assets/75730c1b-6205-4318-878a-71489439f160)

@pawan-live @Movin21

2025-01-10 18:42 UTC, pawan-live approved these changes
Will merge now and fix later

2025-01-10 18:42 UTC, merged